# docker-compose.yml
version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: tms-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  # optional: mongodb express for UI
  # mongo-express:
  #   image: mongo-express
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #   ports:
  #     - "8081:8081"
volumes:
  mongo-data:
